error: adapt rustls_result for upstream changes. (#303)
This commit adapts the `rustls_result` enum based on the changes
upstream. Notably the `CertInvalidEncoding`, `CertInvalidSignatureType`
and `CertInvalidData` errors have been folded into a new
`CertificateError` enum that we expand out into its possible variants.
Similarly the `CorruptMessage` and `CorruptMessagePayload` types have
been replaced by a `InvalidMessage` enum that we expand out.