error: ClientCertVerifierBuilderError -> VerifierBuilderError
This commit updates references to `ClientCertVerifierBuilderError` to
track the upstream rename to `VerifierBuilderError`.