connection: fix clippy redundant_locals finding
After removing the type hints, this is now a redundant binding:

```
error: redundant redefinition of a binding `cs`
   --> src/connection.rs:412:17
    |
412 |                 let cs = cs;
    |                 ^^^^^^^^^^^^
    |
help: `cs` is initially defined here
   --> src/connection.rs:408:17
    |
408 |             for cs in ALL_CIPHER_SUITES {
    |                 ^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
    = note: `#[deny(clippy::redundant_locals)]` on by default
```