error: reduce visibility of mod internal fns
`map_crl_error()` and `map_ech_error()` have no mod-external
crate-internal callers and so don't need to be `pub(crate)`.