error: use decl+proc macro to generate u32 mapping
This works because cbindgen does not need to expand derive macros
to see the enum items, and cbindgen does not care about the existence
of `impl From<u32>` for the rust type that the derive outputs.