error: fixup invalid message errors. (#310)
The `UnsupportedCurve`, `InvalidCertificateStatusType` and `KeyUpdateRequest`
variants of the upstream `InvalidMessage` variants were changed to
remove subvariants that leaked internal API details.

This commit adjusts rustls-ffi error handling to follow. Also, since the
`UnsupportedCurve` error was renamed upstream to `UnsupportedCurveType`
we do the same here.

Lastly, the `Cargo.lock` is updated to bring in the new upstream
changes.