error: properly map new CertificateError::*Context errs
For now we don't have a nice way to expose the details, but we can at
least consistently map them to the relevant `rustls_result` instead of
the catch-all `RUSTLS_RESULT_GENERAL`.